### ISSUE TITLE
Can't import reactotron package

### ISSUE THREAD

**Issue by derekyau** [skellock/reactotron#16]
I can't seem to import the reactotron package.

in my .js file, I try to `import Reactotron from 'reactotron'` but I get a module parse error something like:

`ERROR in ./~/reactotron/index.js
Module parse failed: /path/to/file.js Line 2: Unexpected token
You may need an appropriate loader to handle this file type.
| 
| import Client from './client/reactotron/client'
| 
| export default Client
 @ ./App/Web/Store/Store.js 16:16-37`

I seem to have the correct webpack config my jsxLoader look like:
`jsxLoader.push('babel-loader?presets[]=react,presets[]=es2015,presets[]=stage-0,plugins[]=babel-plugin-transform-es2015-modules-commonjs');`

which is hooked up to the test:
`  {
    test: /\.jsx?$/,
    exclude: /node_modules/,
    loaders: jsxLoader
  }`

which I have the same presets/plugins that are used in the repo, but for some reason it doesn't seem to compile properly.

thanks @skellock for making an awesome contribution, this is gonna go a long way!

**Comment by skellock** [comment]
I think my way out of this is to babel transpile and distribute that as the library instead.   

Thanks man!  Standby.

**Comment by Hyra** [comment]
I was going crazy with my webpack config as well. Standing by!

Thanks for your efforts, sir.

**Comment by skellock** [comment]
Ok, we are now babelifying on our end.  0.3.0 is now out.  Give that a shot lemme know.
