### ISSUE TITLE
Attempting to build client

### ISSUE THREAD

**Issue by GantMan** [skellock/reactotron#19]
verified on my machine and another person's (@fvonhoven) - babelHelper.typeof

### Steps
1. `cd reactotron`
2. `npm i`
3. `cd client`
4. `npm i`
5. `react-native run-ios`

![simulator screen shot apr 21 2016 11 51 23 am](https://cloud.githubusercontent.com/assets/997157/14724485/138d4d0a-07dc-11e6-8b7e-931a5c9c00cc.png)

**Comment by skellock** [comment]
Verified here too after I nuked my node_modules and reconstructed it.

I think what I'll do is split up the 3 sample runtimes a little better.  Thank you @GantMan and @fvonhoven !  i'll get this patched up.

**Comment by skellock** [comment]
I ended up reorganizing stuff.  There was indeed collisions because of the nested npm packages.  So strange.  I've never seen that before.

So now... there's `examples` and `src`.

See the notes in the `examples/README.md` for the one caveat about the `client.js` file.
