### ISSUE TITLE
Action timestamps are reporting 0ms now.

### ISSUE THREAD

**Issue by skellock** [skellock/reactotron#38]
Noticing timestamps on the actions (the middleware) aren't working any longer.  

Probably something simple.  This coincided with the rebase and hand resolving.  Classic @skellock.

**Comment by skellock** [comment]
It seems to actually be the new `storeEnhancer`.  The performance tracking seems to wrap the dispatching of the action through the enhancer chain and not the execution of the action itself.

Taking that out and just using our middleware works great.  So it's not the new timing callbacks (which is kinda cool actually).

Still investigating.

/cc @andrewvy

**Comment by andrewvy** [comment]
Thanks for debugging. I guess my understanding of the store enhancer isn't quite right or my implementation is off, I thought it should be able to wrap the root reducer and be able to call rest of the reducer.
