### ISSUE TITLE
React Native: Store enhancer is not a function 

### ISSUE THREAD

**Issue by ahmed1490** [skellock/reactotron#39]
<img width="277" alt="screenshot" src="https://cloud.githubusercontent.com/assets/623510/14764256/8562ca32-09b1-11e6-8ea4-389cbab3786e.png">

Code..
<img width="759" alt="screenshot" src="https://cloud.githubusercontent.com/assets/623510/14764254/704fea80-09b1-11e6-89b5-5d2819749889.png">

**Comment by skellock** [comment]
The store enhancer just landed in `master` this morning.  A build hasn't been cut yet though.  It'll be `0.5.0` later tonight or early tomorrow.

Can you verify you're installing `0.4.0`?  Or are you indeed off `master` here?

**Comment by ahmed1490** [comment]
You are right! I was in 0.4.0 :)

**Comment by skellock** [comment]
Alrighty, 0.5.0 is on its way to the press.  This contains the new store enhancer.  Lemme know if you have any problems at all!
