### ISSUE TITLE
Subscribing to an object

### ISSUE THREAD

**Issue by FakeYou** [skellock/reactotron#46]
It would be nice if we were able to subscribe to an object, currently when you subscribe to an object you only see `[object Object]`.

**Comment by skellock** [comment]
Thanks for the issue.   The problem with this is:  how deep to you traverse?  What if that object has another object.  The current app I'm building has a pretty deep tree.  In my case, I wouldn't want to traverse past 1 level.

But, did you know...

You can type `user.*`?    That will auto grab each key for you.

**Comment by FakeYou** [comment]
That `user.*` is just what I wanted, thanks! 

Awesome project btw!

**Comment by skellock** [comment]
Thank you!  Once we get #11 implemented, there will be a little nicer way to add watches.
