### ISSUE TITLE
why not using react-blessed?

### ISSUE THREAD

**Issue by kidwm** [skellock/reactotron#47]
and BTW, don't you think the name "Reactron" is more powerful!

https://en.wikipedia.org/wiki/Reactron

**Comment by skellock** [comment]
The original plan was to use `react-blessed`.  I felt i needed to checkout `blessed` first.  It was so easy that I never came back to `react-blessed`.

I think the next step in the UI is to implement the grid system found in `blessed-contrib` though.

Reactron looks pretty bad-ass.  This library, however, is Irish.
