### ISSUE TITLE
Unable to resolve module fbjs/lib/performanceNow

### ISSUE THREAD

**Issue by avioli** [skellock/reactotron#49]
Got an error while using Reactotron: `Unable to resolve module fbjs/lib/performanceNow`.

The issue is that `fbjs` is not a dependency of this project, of course.

When running `npm3+` it is assumed that it will exist because of `react` or even `react-native` has it as a dependency. Unfortunately, when I got the error I was not running `npm3`, but `npm 2.14.12`, which keeps all modules' sub-modules within their respective sub-directory.

Please, add a note that this is a project that only compiles when installed, using `npm3+`, or add `fbjs` as a direct dependency to this project.

**Comment by avioli** [comment]
I'm using `node 4.3.1`, so the Requirement of `4.x+` is ticked.

**Comment by skellock** [comment]
Thank you for the info.  I'll see if I can remove fbjs entirely first. I am only using it for performing timing.

**Comment by skellock** [comment]
I removed this dependency and brought the 3 lines of code into the project. 

Thanks @avioli for calling that out.

`0.6.1` is now live with this fix.
