### ISSUE TITLE
How to run on startup [question]

### ISSUE THREAD

**Issue by amirfl** [skellock/reactotron#80]
I'm trying to follow the suggestion from the readme to start the Reactotron server from the script section of package.json, but can't really get it to work. I'm running it for a react-native project.
Reactotron runs fine when I type
$ node_modules/.bin/reactotron
in the command line.

I've tried 
    `"scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start && node_modules/.bin/reactotron"
  },`
and other variations with no success.
Does anyone have an example on how to implement this?

**Comment by skellock** [comment]
I'd recommend running these as two different tasks.  So keep the npm start task as is, and then add another entry for `{ "tron": "node_modules/.bin/reactotron" }`.

Then in 2 terminal sessions run 1 of each.
